### ISSUE TITLE
Error when dispatching an Event

### ISSUE THREAD

**Issue by avolutions** [avolutions/avolutions#39]
If a Event is dispatched (Application Event or manually) the EventListener is not called and the following Exception can be found in the log file:

> ErrorException: call_user_func() expects parameter 1 to be a valid callback, non-static method Application\Listener\TestEventListener::handleEvent() should not be called statically in C:\xampp\htdocs\avolutions\src\Event\EventDispatcher.php:58
> Stack trace:
> #0 [internal function]: Avolutions\Core\ErrorHandler->handleError(8192, 'call_user_func(...', 'C:\\xampp\\htdocs...', 58, Array)
> #1 C:\xampp\htdocs\avolutions\src\Event\EventDispatcher.php(58): call_user_func(Array, Object(Application\Event\TestEvent))
> #2 C:\xampp\htdocs\avolutions\application\Controller\DefaultController.php(22): Avolutions\Event\EventDispatcher::dispatch(Object(Application\Event\TestEvent))
> #3 [internal function]: Application\Controller\DefaultController->indexAction()
> #4 C:\xampp\htdocs\avolutions\src\Http\Request.php(78): call_user_func_array(Array, Array)
> #5 C:\xampp\htdocs\avolutions\public\index.php(35): Avolutions\Http\Request->send()
> #6 {main}

**Comment by avolutions** [comment]
Will be fixed in 0.4.0-alpha
