### ISSUE TITLE
Entity events leads to an error if the Listener does not exist.

### ISSUE THREAD

**Issue by avolutions** [avolutions/avolutions#41]
If an entity event is dispatch and the matching listener does not exists we receive the following error:

Fatal error: Uncaught Error: Class 'Application\Listener\CounterListener' not found in C:\xampp\htdocs\avolutions.de\src\Event\EventDispatcher.php:38 Stack trace: #0 C:\xampp\htdocs\avolutions.de\src\Orm\Entity.php(90): Avolutions\Event\EventDispatcher::dispatch(Object(Avolutions\Event\EntityEvent)) #1 C:\xampp\htdocs\avolutions.de\application\Service\CounterService.php(16): Avolutions\Orm\Entity->save() #2 C:\xampp\htdocs\avolutions.de\application\Controller\DefaultController.php(13): Application\Service\CounterService::count() #3 [internal function]: Application\Controller\DefaultController->pageAction('index') #4 C:\xampp\htdocs\avolutions.de\src\Http\Request.php(78): call_user_func_array(Array, Array) #5 C:\xampp\htdocs\avolutions.de\public\index.php(35): Avolutions\Http\Request->send() #6 {main} thrown in C:\xampp\htdocs\avolutions.de\src\Event\EventDispatcher.php on line 38

**Comment by avolutions** [comment]
Will be available in 0.4.0-alpha
